# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hamux',
                'doc_host': 'https://bhoov.github.io',
                'git_url': 'https://github.com/bhoov/hamux',
                'lib_path': 'hamux'},
  'syms': {'hamux.core': {'hamux.core.foo': ('core.html#foo', 'hamux/core.py')}}}