# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ham.ipynb.

# %% auto 0
__all__ = ['HAM']

# %% ../nbs/03_ham.ipynb 2
import jax
import jax.numpy as jnp
from typing import *
import treex as tx
from .layers import Layer
from .synapses import Synapse
import jax.tree_util as jtu
from .utils import pytree_save, pytree_load, to_pickleable, align_with_state_dict
import pickle
import functools as ft
from fastcore.utils import *
from abc import ABC, abstractmethod, abstractproperty

# %% ../nbs/03_ham.ipynb 6
class HAM(tx.Module):
    layers: List[Layer]
    synapses: List[Synapse]
    connections: List[Tuple[Tuple, int]]

    def __init__(self, layers, synapses, connections):
        self.layers = layers
        self.synapses = synapses
        self.connections = connections

    @property
    def n_layers(self):
        return len(self.layers)

    @property
    def n_synapses(self):
        return len(self.synapses)

    @property
    def n_connections(self):
        return len(self.connections)

    @property
    def layer_taus(self):
        return [layer.tau for layer in self.layers]

