name: hamux
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip>=20.0
  - nb_conda # Assumes jupyter and jupyter_contrib_nbextensions are globally installed
  - cudatoolkit
  - cudnn